on: push
name: Push
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8' 
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
    - name: Run pytest
      run: ./.github/scripts/run-tests.sh
      shell: bash