name: Tests
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
    steps:
    - uses: actions/checkout@v3
    - name: python ${{ matrix.python-version }} 
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }} 
        cache: 'pip' # caching pip dependencies
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
    - name: Run pytest
      run: ./.github/scripts/run-tests.sh
      shell: bash